sudo: false
language: ruby

rvm:
  - 2.4.1
  - 2.4.0
  - 2.3.3
  - ruby-head

services:
  - docker

install:
  - script/bootstrap no-update
  - script/docker-build $DOCKER_IMAGE:$TRAVIS_COMMIT

env:
  - DOCKER_IMAGE=kryestofer/krye.io

script:
  - script/test
  - script/docker-exec $DOCKER_IMAGE:$TRAVIS_COMMIT script/test

deploy:
  - provider: script
    script: script/docker-build-and-deploy $DOCKER_IMAGE:HEAD
    on:
      ruby: 2.4.1
      branch: master

  - provider: script
    script: script/docker-build-and-deploy $DOCKER_IMAGE:$TRAVIS_TAG
    on:
      ruby: 2.4.1
      tags: true
