---
language: ruby

env:
  - DOCKER_IMAGE=kryestofer/krye.io

jobs:
  include:
    - &test_base
      stage: test
      rvm: ruby-head
      cache: bundler
      install:
        - BUNDLE_PATH=vendor/bundle script/bootstrap no-update
      script:
        - BUNDLE_PATH=vendor/bundle bundle exec rake ci
      after_success:
        - BUNDLE_PATH=vendor/bundle bundle exec codeclimate-test-reporter
    - <<: *test_base
      rvm: 2.4.2
      after_success: skip
    - <<: *test_base
      rvm: 2.3.5
      after_success: skip

    - stage: build and deploy
      sudo: required
      dist: trusty
      rvm: 2.4.2

      services:
        - docker

      install:
        - BUNDLE_PATH=vendor/bundle script/bootstrap no-update
        - script/docker-build $DOCKER_IMAGE:$TRAVIS_COMMIT

      script: skip

      deploy:
        - provider: script
          script: script/docker-deploy $DOCKER_IMAGE:$TRAVIS_COMMIT $DOCKER_IMAGE:HEAD
          on:
            branch: master

        - provider: script
          script: script/docker-deploy $DOCKER_IMAGE:$TRAVIS_COMMIT $DOCKER_IMAGE:$TRAVIS_TAG
          on:
            tags: true

        - provider: script
          script: script/docker-deploy $DOCKER_IMAGE:$TRAVIS_COMMIT $DOCKER_IMAGE:$TRAVIS_TAG $DOCKER_IMAGE:latest
          on:
            condition: $(script/github-latest-release) == $TRAVIS_TAG
            tags: true
