sudo: false
language: ruby

rvm:
  - 2.4.1
  - 2.4.0
  - 2.3.3
  - ruby-head

services:
  - docker

install:
  - script/bootstrap no-update

env:
  - DOCKER_IMAGE=kryestofer/krye.io

script:
  - bundle exec rake spec
  - script/docker-build $DOCKER_IMAGE:$TRAVIS_COMMIT
  - script/docker-exec $DOCKER_IMAGE:$TRAVIS_COMMIT script/self-check

deploy:
  - provider: script
    script:
      - script/docker-build $DOCKER_IMAGE:HEAD
      - script/docker-deploy $DOCKER_IMAGE:HEAD
    on:
      rvm:
        - 2.4.1
      branch: master

  - provider: script
    script:
      - script/docker-build $DOCKER_IMAGE:$TRAVIS_TAG
      - script/docker-deploy $DOCKER_IMAGE:$TRAVIS_TAG
    on:
      rvm:
        - 2.4.1
      tags: true
