version: '2'
services:
  redis:
    image: redis
    expose:
      - '6379'
    volumes:
      - "./config/redis.conf:/etc/redis.conf"
    command: "redis-server /etc/redis.conf"

  web-production-9300:
    image: kryestofer/krye.io:latest
    ports:
      - '9300:80'
    links:
      - redis

  web-production-9301:
    image: kryestofer/krye.io:latest
    ports:
      - '9301:80'
    links:
      - redis

  web-production-9302:
    image: kryestofer/krye.io:latest
    ports:
      - '9302:80'
    links:
      - redis

  web-production-9303:
    image: kryestofer/krye.io:latest
    ports:
      - '9303:80'
    links:
      - redis

  web-staging-9200:
    image: kryestofer/krye.io:HEAD
    ports:
      - '9200:80'
    environment:
      - REDIS_PASSWORD
      - REDIS_HOST=redis-server
    links:
      - "redis:redis-server"
