version: '2'
services:
  redis:
    image: redis
    restart: unless-stopped
    expose:
      - '6379'
    volumes:
      - './config/redis.conf:/etc/redis.conf:Z'
    command: 'redis-server /etc/redis.conf'

  web-production-9300:
    image: kryestofer/krye.io:latest
    restart: unless-stopped
    ports:
      - '9300:80'
    environment:
      - REDIS_PASSWORD
      - REDIS_HOST=redis-server
    links:
      - 'redis:redis-server'

  web-production-9301:
    image: kryestofer/krye.io:latest
    restart: unless-stopped
    ports:
      - '9301:80'
    environment:
      - REDIS_PASSWORD
      - REDIS_HOST=redis-server
    links:
      - 'redis:redis-server'

  web-staging-9200:
    image: kryestofer/krye.io:HEAD
    restart: unless-stopped
    ports:
      - '9200:80'
    environment:
      - REDIS_PASSWORD
      - REDIS_HOST=redis-server
    links:
      - 'redis:redis-server'
