environments:
  __default__:
    root_directory: '..'

    'views':
      'index.html.erb':
        cache: true
        aliases:
          - '/'
          - '/index.html'

      'resume.html.erb':
        cache: true
        aliases:
          - '/resume'
          - '/resume.html'

      'css':
        !ruby/regexp '/(.+).scss':
          cache: true
          format: 'scss'
          aliases:
            - '/css/$1.css'


environment: production
