#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.expand_path(File.join(File.dirname(__FILE__), 'lib')))
$LOAD_PATH.unshift(File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib')))

# Require the entire `script` lib tree.
require 'script'

require 'site/logger'

Site::Logger.info "Starting bootstrapping process..."

Site::Logger.info "Running `script/update`"

# Run `script/update` to make sure everything is up-to-date.
Runner.run("script/update") do |output_line|
	Site::Logger.debug output_line.chomp
end

Site::Logger.info "Running `bundle install`"

# Run `bundle install` to install our dependencies.
Runner.run("bundle", "install") do |output_line|
	Site::Logger.debug output_line.chomp
end
