#!/usr/bin/env ruby

require 'pty'

DOCKER = `which docker`.strip

raise "Docker does not seem to be installed.  Please make sure that it is.  (#{DOCKER})" unless $? == 0




pid = fork do


end

puts "Child process spawned (pid: #{pid})"

Process.waitpid(pid)
