#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.expand_path(File.join(File.dirname(__FILE__), 'lib')))
$LOAD_PATH.unshift(File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib')))

# Require the entire `script` lib tree.
require 'script'

require 'site/logger'

Site::Logger.info "Verifying credentials..."

raise RuntimeError, "DOCKER_USERNAME not set!" unless ENV['DOCKER_USERNAME']
raise RuntimeError, "DOCKER_PASSWORD not set!" unless ENV['DOCKER_PASSWORD']

`docker login -u="#{ENV['DOCKER_USERNAME']}" -p="#{ENV['DOCKER_PASSWORD']}"`

raise RuntimeError, "Docker login failed!" unless $? == 0

Site::Logger.info "Starting Docker push process..."

DOCKER_TAG_REGEXP = /([\w\.\/]+):?([\w\.\/]+)?/

tags = ARGV.grep(DOCKER_TAG_REGEXP)

source_tag = tags.first
aliases = tags[1..-1]

Site::Logger.info "Source tag: #{source_tag}"
Site::Logger.info "Deploy targets (#{aliases.count}): #{aliases.join(' ')}"

aliases.each_with_index do |alyas, index|
	Site::Logger.info "Tagging #{source_tag} as #{alyas}..."

	command = ['docker', 'tag', source_tag, alyas]

	Site::Logger.info "Running `#{command.join(' ')}`..."

	Runner.run(command) do |output_line|
		Site::Logger.debug output_line.chomp
	end
end

Site::Logger.info "Pushing #{aliases.count} tags..."

aliases.each_with_index do |alyas, index|
	command = ["docker", "push", "#{alyas}"]

	Site::Logger.info "Running `#{command.join(' ')}`..."

	Runner.run(command) do |output_line|
		Site::Logger.debug output_line.chomp
	end
end
