#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.expand_path(File.join(File.dirname(__FILE__), 'lib')))
$LOAD_PATH.unshift(File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib')))

# Require the entire `script` lib tree.
require 'script'

require 'site/logger'

DOCKER_TAG_REGEXP = /([\w\.\/]+):?([\w\.\/]+)?/

raise RuntimeError, "DOCKER_USERNAME not set!" unless ENV['DOCKER_USERNAME']
raise RuntimeError, "DOCKER_PASSWORD not set!" unless ENV['DOCKER_PASSWORD']

`docker login -u="#{ENV['DOCKER_USERNAME']}" -p="#{ENV['DOCKER_PASSWORD']}"`

tag = ARGV[0]

Site::Logger.info "Starting build and deploy process..."

Site::Logger.info "Bulding tag #{tag}..."

command = ["script/docker-build", tag]

Site::Logger.info "Running `#{command.join(' ')}`"

Runner.run(command) do |output_line|
	Site::Logger.debug output_line.chomp
end

Site::Logger.info "Pushing tag #{tag}..."

command = ["script/docker-push", tag]

Site::Logger.info "Running `#{command.join(' ')}`"

Runner.run(command) do |output_line|
	Site::Logger.debug output_line.chomp
end
