#!/usr/bin/env ruby

require 'pty'

DOCKER = `which docker`.strip

raise "Docker does not seem to be installed.  Please make sure that it is.  (#{DOCKER})" unless $? == 0

@image = ARGV[0]
@name = ARGV[1]

@args = ARGV[2..-1]

puts "Running #{DOCKER}..."
puts " -> pull #{@image}"
puts " -> rm #{@name}"
puts " -> run --name=#{@name} #{@args.join(' ')} #{@image}"

pid = fork do

	system "#{DOCKER} pull #{@image}"
	system "#{DOCKER} rm #{@name}"
	system "#{DOCKER} run --name=#{@name} #{@args.join(' ')} #{@image}"

end

puts "Child process spawned (pid: #{pid})"

Process.waitpid(pid)
