#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.expand_path(File.join(File.dirname(__FILE__), 'lib')))
$LOAD_PATH.unshift(File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib')))

# Require the entire `script` lib tree.
require 'script'

puts "Running test suite..."

puts "Running `bundle exec rake spec`"

command = ["bundle", "exec", "rake", "spec"]

Runner.run(command) do |output_line|
	puts output_line.chomp
end
