#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.expand_path(File.join(File.dirname(__FILE__), 'lib')))
$LOAD_PATH.unshift(File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib')))

# Require the entire `script` lib tree.
require 'script'

puts "Starting update process..."

puts "Running `git fetch`"

Runner.run("git", "fetch") do |output_line|
	puts output_line.chomp
end

puts "Running `git merge`"
puts "Note: This will fail if you happen to not have your MERGE_HEAD set on your current branch."

Runner.run("git", "merge") do |output_line|
	puts output_line.chomp
end

puts "Running `bundle`"

Runner.run("bundle") do |output_line|
	puts output_line.chomp
end

puts "Running `bundle exec rspec`"

begin
	Runner.run("bundle", "exec rspec") do |output_line|
		puts output_line.chomp
	end

rescue Exception => error
	puts error
end
